### ISSUE TITLE
Is it possible to place symlink into folder ?

### ISSUE THREAD

**Issue by danielstaleiny** [krebs/krops#13]
Hi, thanks for this awesome project, makes my life easier. 

Is it possible to create symlink in folder under /var/src for example ?

I tried 
```
      "nixos".file = toString ./nixos;
      "nixos/configuration.nix".symlink = "/etc/nixos/configuration.nix";
```
```
      "nixos".file = toString ./nixos;
      "/var/src/nixos/configuration.nix".symlink = "/etc/nixos/configuration.nix";
```
```
      "nixos".file = toString ./nixos;
      nixos."configuration.nix".symlink = "/etc/nixos/configuration.nix";
```

without succes.

**Comment by 4z3** [comment]
It's indirectly possible by already having the symlink in the folder.

In particular:
1. create symlink in `./nixos` (`ln -s /etc/nixos/configuration.nix ./nixos`)
1. keep only `nixos.file = toString ./nixos;`
