### ISSUE TITLE
Allow specifying an empty target user [feature]

### ISSUE THREAD

**Issue by ghost** [krebs/krops#2]
In our team we use krops, and everyone has already set up their ~/.ssh/config to set the correct username and ports for the target hosts.
I would like to be able to set the target user to an empty string, and let krops omit the "user@" part completely, so that the values from ~/.ssh/config are used.

**Comment by 4z3** [comment]
https://github.com/krebs/krops/pull/5 adds this feature. To use it, the target has to explicitly set the user to the empty string, i.e. something like `"@host/path"`. It looks a bit funny, but we have to do it like that as `"host/path"` already means to use `LOGNAME` and we cannot break existing setups. @petabyteboy, please let me know it that solution works for you, then I'm going to merge it.

**Comment by ghost** [comment]
Yes, this looks like a great solution to me :+1: 
Thanks :)
