### ISSUE TITLE
sudo on remote host [feature]

### ISSUE THREAD

**Issue by ghost** [krebs/krops#3]
I want to deploy to hosts where I don't have ssh access to the root user, but I have passwordless sudo. 
I have implemented a hard-coded version here:
https://github.com/nyantec/krops/commit/b4d8f75d6a805796a5a9cbc2a43326682ca63371

**Comment by 4z3** [comment]
I think the main question is how to make this configurable. I'm not sure if we can sanely configure it via the target string, i.e. somewhere within `"user@host:port/path"`, but we certainly could accept pre-parsed target arguments in `writeDeploy` & co.. Then sudo could be enabled like this:
```nix
pkgs.krops.writeDeploy "deploy" {
  source = /* ... */;
  target = lib.mkTarget "user@host/path" // {
    sudo = true; 
  };
}
```
