### ISSUE TITLE
Official communication channel?

### ISSUE THREAD

**Issue by matthiasbeyer** [krebs/krops#31]
As freenode is dead (as in freenode), what is the official channel for communication for this project?

**Comment by Lassulus** [comment]
fixed in https://github.com/krebs/krops/commit/b78e4d5a925d2987b52b33e98c3aeae12c41d019
Thanks!

**Comment by 4z3** [comment]
That said, we're still reachable via freenode for now, as well as liberachat, just in case. Also, mail still works, too.
