### ISSUE TITLE
Usage on non-NixOS Platforms?

### ISSUE THREAD

**Issue by matthiasbeyer** [krebs/krops#32]
Hi,

I guess krops can also be used to deploy non-nixos systems (e.g. ubuntu with nix installed) somehow? With `writeCommand` maybe somehow?

Would be nice if there was an example for that! :smile:

**Comment by mrVanDalo** [comment]
I never used nix without NixOS. Isn't nix just a package manager? So there is no module system, just pkgs. You can't manipulate systemd or anything in `/etc` using just the nix package manager. So what do you want to provision?
Or am I wrong?

**Comment by matthiasbeyer** [comment]
Yes, the idea was to just deploy package sets to a non-nixos host. Like user environments and so on, nothing in the actual system!

**Comment by Lassulus** [comment]
can this be done with writeCommand?

**Comment by mrVanDalo** [comment]
Yes this can be done with `writeCommand`. But you deployment depends heavily on what you want. For example I use home-manager and flakes on my work machine. Another person would use plain nix. So you are on you own using `writeCommand`, I guess.
